### PR TITLE
Nosetests py3

### PR DESCRIPTION
**Pull request by j-friedrich**
Fixes, or rather circumvents, the error on MacOS with ipyparallel and cython by running OASIS in parallel only on Linux but not on Mac.

Unittests run out of the box on Linux by simply executing `nosetests` in the CaImAn rootdirectory (or in CaImAn/caiman or CaImAn/caiman/tests). 
On Mac they have to be be called directly within the directory CaImAn/caiman/tests, e.g.
`cd caiman/tests`
`ls test_*py | while read t; do nosetests --nologcapture ${t%%.py}; done;`

### CODE REVIEW

**Comment by outlace** [comment]
I'm on Mac OS and haven't had any issues with ipyparallel

**Comment by j-friedrich** [comment]
Hi Brandon, you've not been using the caiman1.0 branch but the master branch, have you? I moved more code from python to C++ (cython), which makes the deconvolution up to 10x faster, but oddly apparently doesn't work with ipyparallel on Mac OS. If caiman1.0 with ipyparallel really works without issues for you (e.g. test_parallel() in test_demo.py), then please let me know your installed package versions.

**Comment by outlace** [comment]
I just installed CaImAn per instructions in readme for Mac OS. caiman.__version__ doesn't work for me, but looking at setup.py it says caiman version 0.1 not 1.0
I just ran test_demo test_parallel(), this is the output, looks like it works for me:
```python
(caiman) Brandons-MacBook-Air:tests brandonbrown$ python
Python 3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 12:43:10) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from caiman.tests import test_demo
test_demoKERAS NOT INSTALLED. IF YOU WANT TO USE THE CNN BASED COMPONENT CLASSIFIER (experimental) CONTACT THE DEVELOPERS
>>> test_demo.test_parallel()
Stopping cluster...
NOT SLURM
No cluster to stop... done
Starting cluster...Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json
2017-09-27 10:59:13.442 [IPClusterStart] Starting ipcluster with [daemon=False]
2017-09-27 10:59:13.443 [IPClusterStart] Creating pid file: /Users/brandonbrown/.ipython/profile_default/pid/ipcluster.pid
2017-09-27 10:59:13.443 [IPClusterStart] Starting Controller with LocalControllerLauncher
2017-09-27 10:59:14.453 [IPClusterStart] Starting 4 Engines with LocalEngineSetLauncher
......../../example_movies/demoMovie.tif
(2000, 60, 80)
using 2 processes
using 4000 pixels per process
using 20000 block_size
preprocessing ...
checking if missing data
Running on 4 engines.
initializing ...
Noise Normalization
Spatial Downsampling ...
Roi Extraction...
Greedy initialization of spatial and temporal components using spatial Gaussian filtering
USING TOTAL SUM FOR INITIALIZATION....
(Hals) Refining Components...
/Users/brandonbrown/anaconda/envs/caiman/lib/python3.5/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
update spatial ...
Initializing update of Spatial Components
computing the distance indicators
found spatial support for each component
memmaping
Updating Spatial Components using lasso lars
thresholding components
Computing residuals
parallel dot product block size: 1000
Start product
Filling
--- 11.317582130432129 seconds ---
Removing tempfiles created
update temporal ...
deconvolution ...
Generating residuals
parallel dot product block size: 20000
Start product
Transposing
4799
entering the deconvolution 
9 out of total 30 temporal components updated
17 out of total 30 temporal components updated
23 out of total 30 temporal components updated
27 out of total 30 temporal components updated
30 out of total 30 temporal components updated
9 out of total 30 temporal components updated
17 out of total 30 temporal components updated
23 out of total 30 temporal components updated
27 out of total 30 temporal components updated
30 out of total 30 temporal components updated
stopping: overall temporal component not changing significantly
refinement...
merge components ...
/Users/brandonbrown/anaconda/envs/caiman/lib/python3.5/site-packages/scipy/sparse/compressed.py:774: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
[ 0 12]
[ 1 14]
(4800, 28)
update spatial ...
Initializing update of Spatial Components
computing the distance indicators
found spatial support for each component
memmaping
Updating Spatial Components using lasso lars
thresholding components
Computing residuals
parallel dot product block size: 1000
Start product
Filling
--- 5.070674896240234 seconds ---
Removing tempfiles created
update temporal ...
Generating residuals
parallel dot product block size: 20000
Start product
Transposing
4799
entering the deconvolution 
6 out of total 28 temporal components updated
14 out of total 28 temporal components updated
2017-09-27 10:59:44.800 [IPClusterStart] Engines appear to have started successfully
19 out of total 28 temporal components updated
24 out of total 28 temporal components updated
26 out of total 28 temporal components updated
27 out of total 28 temporal components updated
28 out of total 28 temporal components updated
6 out of total 28 temporal components updated
14 out of total 28 temporal components updated
19 out of total 28 temporal components updated
24 out of total 28 temporal components updated
26 out of total 28 temporal components updated
27 out of total 28 temporal components updated
28 out of total 28 temporal components updated
stopping: overall temporal component not changing significantly
Stopping cluster...
NOT SLURM
Waiting for cluster to stop....2017-09-27 10:59:47.662 [IPClusterStart] ERROR | IPython cluster: stopping
2017-09-27 10:59:47.662 [IPClusterStart] Stopping Engines...
...2017-09-27 10:59:50.667 [IPClusterStart] Removing pid file: /Users/brandonbrown/.ipython/profile_default/pid/ipcluster.pid
 done
```

**Comment by outlace** [comment]
And here are my installed package versions:

```bash
(caiman) Brandons-MacBook-Air:tests brandonbrown$ pip freeze
alabaster==0.7.10
anaconda-client==1.6.3
appnope==0.1.0
astroid==1.5.3
Babel==2.5.0
bkcharts==0.2
bleach==1.5.0
bokeh==0.12.7
certifi==2016.2.28
chardet==3.0.4
clyent==1.2.2
cycler==0.10.0
Cython==0.26
decorator==4.1.2
docutils==0.14
entrypoints==0.2.3
future==0.16.0
h5py==2.7.0
html5lib==0.9999999
imagesize==0.7.1
ipykernel==4.6.1
ipyparallel==6.0.2
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.15
jedi==0.10.2
Jinja2==2.9.6
JSAnimation==0.1
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
lazy-object-proxy==1.3.1
llvmlite==0.20.0
mapper==0.1.13
MarkupSafe==1.0
matplotlib==2.0.2
mistune==0.7.4
nb-anacondacloud==1.4.0
nb-conda==2.2.0
nb-conda-kernels==2.1.0
nbconvert==5.2.1
nbformat==4.4.0
nbpresent==3.0.2
networkx==1.11
nose==1.3.7
notebook==5.0.0
numba==0.35.0
numpy==1.13.1
numpydoc==0.7.0
olefile==0.44
pandas==0.20.3
pandocfilters==1.4.2
patsy==0.4.1
PeakUtils==1.1.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.2.1
prompt-toolkit==1.0.15
psutil==5.2.2
ptyprocess==0.5.2
pycodestyle==2.3.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.7.2
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
requests==2.14.2
rope-py3k==0.9.4.post1
scikit-image==0.13.0
scikit-learn==0.19.0
scipy==0.19.1
seaborn==0.8
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.3
statsmodels==0.8.0
terminado==0.6
testpath==0.3
tifffile==0.12.1
tornado==4.5.2
tqdm==4.15.0
traitlets==4.3.2
wcwidth==0.1.7
widgetsnbextension==3.0.2
wrapt==1.10.11
```

**Pull request merged**
